basePath: /api/v1
definitions:
  handlers.CreateMovieRequest:
    properties:
      code:
        type: string
      cover_url:
        type: string
      description:
        type: string
      rating:
        type: number
      series_id:
        type: integer
      studio_id:
        type: integer
      title:
        type: string
    required:
    - code
    - title
    type: object
  handlers.ErrorResponse:
    properties:
      code:
        type: string
      error:
        type: string
      message:
        type: string
    type: object
  handlers.JAVDbMovieSearchResponse:
    properties:
      code:
        type: string
      cover_url:
        type: string
      detail_url:
        type: string
      rating:
        type: number
      release_date:
        type: string
      title:
        type: string
    type: object
  handlers.ListResponse:
    properties:
      items: {}
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  handlers.LocalMovie:
    properties:
      actress:
        type: string
      code:
        type: string
      fanart_path:
        type: string
      fanart_url:
        type: string
      format:
        type: string
      has_fanart:
        type: boolean
      modified:
        type: string
      path:
        type: string
      size:
        type: integer
      title:
        type: string
    type: object
  handlers.Response:
    properties:
      code:
        type: string
      data: {}
      message:
        type: string
    type: object
  model.Actress:
    properties:
      alias:
        items:
          type: string
        type: array
      avatar_url:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      movies:
        description: 关联关系
        items:
          $ref: '#/definitions/model.Movie'
        type: array
      name:
        type: string
      updated_at:
        type: string
    type: object
  model.DownloadTask:
    properties:
      completed_at:
        type: string
      created_at:
        type: string
      downloaded_size:
        type: integer
      error_message:
        type: string
      id:
        type: integer
      movie:
        allOf:
        - $ref: '#/definitions/model.Movie'
        description: 关联关系
      movie_id:
        type: integer
      progress:
        type: integer
      speed:
        description: B/s
        type: integer
      started_at:
        type: string
      status:
        type: string
      total_size:
        type: integer
      updated_at:
        type: string
      url:
        type: string
    type: object
  model.Favorite:
    properties:
      created_at:
        type: string
      id:
        type: integer
      movie:
        allOf:
        - $ref: '#/definitions/model.Movie'
        description: 关联关系
      movie_id:
        type: integer
      updated_at:
        type: string
      user_id:
        description: 预留用户系统
        type: integer
    type: object
  model.Movie:
    properties:
      actresses:
        items:
          $ref: '#/definitions/model.Actress'
        type: array
      code:
        type: string
      cover_url:
        type: string
      created_at:
        type: string
      description:
        type: string
      download_progress:
        type: integer
      download_status:
        type: string
      downloads:
        items:
          $ref: '#/definitions/model.DownloadTask'
        type: array
      duration:
        description: 分钟
        type: integer
      fanart_url:
        type: string
      favorites:
        items:
          $ref: '#/definitions/model.Favorite'
        type: array
      file_format:
        type: string
      file_size:
        type: integer
      has_subtitle:
        type: boolean
      id:
        type: integer
      is_downloaded:
        type: boolean
      last_watched:
        type: string
      local_path:
        type: string
      quality:
        type: string
      rating:
        type: number
      release_date:
        type: string
      series:
        $ref: '#/definitions/model.Series'
      series_id:
        type: integer
      studio:
        allOf:
        - $ref: '#/definitions/model.Studio'
        description: 关联关系
      studio_id:
        type: integer
      subtitle_languages:
        items:
          type: string
        type: array
      tags:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      title:
        type: string
      trailer_url:
        type: string
      updated_at:
        type: string
      watch_count:
        type: integer
      watch_history:
        items:
          $ref: '#/definitions/model.WatchHistory'
        type: array
    type: object
  model.Ranking:
    properties:
      code:
        type: string
      cover_url:
        type: string
      crawled_at:
        description: 爬取时间
        type: string
      created_at:
        type: string
      id:
        type: integer
      last_checked:
        description: 最后检查时间
        type: string
      local_exists:
        description: 是否在本地存在
        type: boolean
      position:
        description: 排名位置
        type: integer
      rank_type:
        description: daily, weekly, monthly
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  model.Series:
    properties:
      created_at:
        type: string
      id:
        type: integer
      movies:
        items:
          $ref: '#/definitions/model.Movie'
        type: array
      name:
        type: string
      studio:
        allOf:
        - $ref: '#/definitions/model.Studio'
        description: 关联关系
      studio_id:
        type: integer
      updated_at:
        type: string
    type: object
  model.Studio:
    properties:
      created_at:
        type: string
      id:
        type: integer
      logo_url:
        type: string
      movies:
        description: 关联关系
        items:
          $ref: '#/definitions/model.Movie'
        type: array
      name:
        type: string
      series:
        items:
          $ref: '#/definitions/model.Series'
        type: array
      updated_at:
        type: string
    type: object
  model.Tag:
    properties:
      category:
        description: genre, quality, etc
        type: string
      created_at:
        type: string
      id:
        type: integer
      movies:
        description: 关联关系
        items:
          $ref: '#/definitions/model.Movie'
        type: array
      name:
        type: string
      updated_at:
        type: string
    type: object
  model.WatchHistory:
    properties:
      created_at:
        type: string
      id:
        type: integer
      movie:
        allOf:
        - $ref: '#/definitions/model.Movie'
        description: 关联关系
      movie_id:
        type: integer
      updated_at:
        type: string
      user_id:
        description: 预留用户系统
        type: integer
      watch_position:
        description: 秒
        type: integer
      watched_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 智能成人影视库管理系统 - 提供影片管理、种子下载、排行榜等功能
  title: NSFW-Go API
  version: "1.0"
paths:
  /api/v1/movies:
    get:
      consumes:
      - application/json
      description: 获取影片列表，支持分页和筛选
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: limit
        type: integer
      - description: 制作商ID
        in: query
        name: studio_id
        type: integer
      - description: 画质
        in: query
        name: quality
        type: string
      - description: 是否有字幕
        in: query
        name: has_subtitle
        type: boolean
      - description: 是否已下载
        in: query
        name: is_downloaded
        type: boolean
      - description: 排序字段
        enum:
        - created_at
        - rating
        - watch_count
        - release_date
        in: query
        name: sort_by
        type: string
      - description: 排序方向
        enum:
        - asc
        - desc
        in: query
        name: sort_order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/handlers.ListResponse'
                  - properties:
                      items:
                        items:
                          $ref: '#/definitions/model.Movie'
                        type: array
                    type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 获取影片列表
      tags:
      - movies
    post:
      consumes:
      - application/json
      description: 创建新的影片记录
      parameters:
      - description: 影片信息
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateMovieRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Movie'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 创建影片
      tags:
      - movies
  /api/v1/movies/{id}:
    get:
      consumes:
      - application/json
      description: 根据影片ID获取详细信息
      parameters:
      - description: 影片ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Movie'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 获取影片详情
      tags:
      - movies
  /api/v1/movies/code/{code}:
    get:
      consumes:
      - application/json
      description: 根据影片番号获取详细信息
      parameters:
      - description: 影片番号
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Movie'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 根据番号获取影片详情
      tags:
      - movies
  /api/v1/movies/popular:
    get:
      consumes:
      - application/json
      description: 获取热门影片列表
      parameters:
      - default: 10
        description: 数量限制
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Movie'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 获取热门影片
      tags:
      - movies
  /api/v1/movies/recent:
    get:
      consumes:
      - application/json
      description: 获取最近添加的影片列表
      parameters:
      - default: 10
        description: 数量限制
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Movie'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 获取最近添加的影片
      tags:
      - movies
  /api/v1/movies/search:
    get:
      consumes:
      - application/json
      description: 根据关键词搜索影片
      parameters:
      - description: 搜索关键词
        in: query
        name: q
        required: true
        type: string
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/handlers.ListResponse'
                  - properties:
                      items:
                        items:
                          $ref: '#/definitions/model.Movie'
                        type: array
                    type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 搜索影片
      tags:
      - movies
  /local/movies:
    get:
      consumes:
      - application/json
      description: 分页获取本地影片库中的影片列表，支持按女优筛选
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 100
        description: 每页数量
        in: query
        name: limit
        type: integer
      - description: 女优筛选
        in: query
        name: actress
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 影片列表
          schema:
            allOf:
            - $ref: '#/definitions/handlers.ListResponse'
            - properties:
                items:
                  items:
                    $ref: '#/definitions/handlers.LocalMovie'
                  type: array
              type: object
        "500":
          description: 获取失败
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 获取本地影片列表
      tags:
      - local
  /local/scan:
    post:
      consumes:
      - application/json
      description: 触发一次完整的本地影片库扫描，更新数据库中的影片信息
      produces:
      - application/json
      responses:
        "200":
          description: 扫描成功
          schema:
            $ref: '#/definitions/handlers.Response'
        "500":
          description: 扫描失败
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 手动扫描本地影片库
      tags:
      - local
  /local/stats:
    get:
      consumes:
      - application/json
      description: 获取本地影片库的统计信息，包括总数、女优数量等
      produces:
      - application/json
      responses:
        "200":
          description: 统计信息
          schema:
            $ref: '#/definitions/handlers.Response'
        "500":
          description: 获取失败
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 获取本地影片统计
      tags:
      - local
  /rankings:
    get:
      consumes:
      - application/json
      description: 获取JAVDb排行榜数据，支持日榜、周榜、月榜
      parameters:
      - default: daily
        description: 排行榜类型
        enum:
        - daily
        - weekly
        - monthly
        in: query
        name: type
        type: string
      - default: 50
        description: 数量限制
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 排行榜列表
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Ranking'
                  type: array
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: 获取失败
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 获取排行榜列表
      tags:
      - rankings
  /search/javdb:
    get:
      consumes:
      - application/json
      description: 在JAVDb网站搜索影片信息，支持番号和标题搜索
      parameters:
      - description: 搜索关键词
        in: query
        name: q
        required: true
        type: string
      - default: movie
        description: 搜索类型
        enum:
        - movie
        - actress
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 搜索结果
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/handlers.JAVDbMovieSearchResponse'
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: 搜索失败
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: JAVDb在线搜索
      tags:
      - search
  /torrents/search:
    get:
      consumes:
      - application/json
      description: 通过Jackett搜索种子文件，支持任意关键词搜索
      parameters:
      - description: 搜索关键词
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 搜索结果
          schema:
            $ref: '#/definitions/handlers.Response'
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: 搜索失败
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 搜索种子文件
      tags:
      - torrents
swagger: "2.0"
