server:
  port: 8080
  mode: release  # debug, release, test

database:
  host: localhost
  port: 5432
  user: nsfw
  password: "your_password_here"
  dbname: nsfw_db
  sslmode: disable
  timezone: Asia/Shanghai
  
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

media:
  base_path: "/MediaCenter/NSFW/Hub/#Done"
  scan_interval: "15m"
  supported_formats: ["mp4", "mkv", "avi", "mov", "wmv"]

crawler:
  javdb_base_url: "https://javdb.com"
  ranking_schedule: "0 12 * * *"    # 每日12:00自动爬取排行榜
  local_check_schedule: "0 * * * *"  # 每小时检查本地匹配
  request_timeout: "30s"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

logging:
  level: info  # debug, info, warn, error
  file: "logs/nsfw-go.log"
  max_size: 100  # MB
  max_backups: 3
  max_age: 28  # days 